= Espresso++: Software Design Document
Giuseppe Greco <giuseppe.greco@skeeterhealth.com>
v.0.1, 23.02.2020: First draft
:sectnums:
:toc:
:toclevels: 3
:description: Espresso++ Software Design Document
:keywords: Espresso++ Software Design
:imagesdir: ./assets/espressopp-sdd
:espressopp: Espresso++

[[introduction]]
== Introduction

=== Purpose of the Document

This document presents the design of {espressopp}, a natural query language that
abstracts the native query language of any data management system, and the
intended audience is anybody involved in its realization.

=== Scope of the "Software Design Document"

This design document applies to any Skeeter API that supports data filtering.

=== Definitions, Acronyms, and Abbreviations

[glossary]
Lexer:: The part of an interpreter that attaches meaning by classifying _lexemes_
(string of symbols from the input) as particular tokens. For example, the _lexemes_
`or`, `and`, and `not` are classified as _logical operators_ by the {espressopp} lexer.

Parser:: The part of an interpreter that attaches meaning by classifying strings of
tokens from the input (sentences) as particular _non-terminals_ and by building the
_parse tree_. For example, token strings like `[number][operator][number]` or
`[id][operator][id]` are classified as _non-terminal expressions_ by the {espressopp} parser.

Interpreter:: A computer program that converts each high-level statement into code or
instructions that can be understood by the underlying system.

Visitor Pattern:: A way of separating an algorithm from the structure on which it operates.
The result of this separation is the ability to add new operations to an existing structure
without modifying the structure itself.

[bibliography]
=== References

- [[[els,1]]] Giuseppe Greco. <<espressopp-spec.adoc#, The {espressopp} Language Specification>>.
  Skeeter Health. 2020.

=== Overview

Skeeter APIs let clients specify a filter to limit or control the data returned by an endpoint.
A filter consists of one or more statements written in {espressopp} <<els>> that abstract away
the native query language of the underlying data management system.

{espressopp} comes as a module together with a command-line utility that converts input
{espressopp} expressions into native expressions that can be understood by the underlying data
management system. The next sections describe what functionality {espressopp} shall provide
and how that functionality shall be implemented.

[[use-case-view]]
== Use Case View

Figure <<use-case-diagram>> shows what fuctionality {espressopp} provides and what external systems
(actors) interact with it.

[[use-case-diagram]]
.Actors, Use Cases, and their Interactions
[plantuml, format="png", id="use-case-diagram"]
----
Client << Aplication >>
(Interpret Espresso++ Script) as (uc1)
(Generate Native Code) as (uc2)
Client -> (uc1)
(uc1) ..> (uc2) : use
----
{empty} +

Use case _Interpret {espressopp} Script_ is started by the _Client_ when an {espressopp} expression
is executed to filter the data returned by an API endpoint. _Interpret {espressopp} Script_ parses
the {espressopp} expression and passes the resulting _parse tree_ to use case _Generate Native Code_,
which in turn generates the native query to be executed by the underlying data management system.

[[logical-view]]
== Logical View

This section describes the logical structure of {espressopp}. The {espressopp} interpreter provides
functionality for translating {espressopp} expressions into native queries. Figure <<key-elements>>
shows the classes that make up {espressopp} and how they depend on each other.

[[key-elements]]
.Key Structural and Behavioral Elements
[plantuml, format="png", id="key-elements"]
----
abstract class Interpreter <<interface>> {
  +Accept(CodeGenerator, Reader, Writer)
  +Parse(Reader): Grammar
}
class EspressoppInterpreter {
  +Accept(CodeGenerator, Reader, Writer)
  +Parse(Reader): Grammar
}
abstract class CodeGenerator <<interface>> {
  +Visit(Interpreter, Reader, Writer)
  +MapFieldNames(Map)
}
class SqlCodeGenerator {
  +Visit(Interpreter, Reader, Writer)
  +MapFieldNames(Map)
}
class Parser{
  +Parse(Reader): Grammar
}
class Grammar{
  +Query: {}
}
Client ..> Interpreter
Client ..> CodeGenerator
Interpreter <|-- EspressoppInterpreter : extends
note left: Call CodeGenerator.Visit(Interpreter, ...)
CodeGenerator <|-- SqlCodeGenerator : extends
EspressoppInterpreter o-- Parser
Grammar --* Parser
----
{empty} +

The design of {espressopp} is based on the _visitor pattern_ so that new `CodeGenerator` implementations
can be added anytime without the need to modify `EspressoppInterpreter`. `SqlCodeGenerator` is the
default `CodeGenerator` implementation shipped with the first release of {espressopp}.

=== Use Case Realization

This section describes how the use cases are implemented and examines how the various design
structures contribute to the functionality of the system. It also describes the collaborations
that realize {espressopp} and contribute to define the dynamic view of the system.

==== Use Case: Interpret {espressopp} Script

This section describes the relationship between use case _Interpret {espressopp} Script_ and the
collaborations that actually realize it.

===== Scenario: Interpret {espressopp} Script

The sequence diagram depicted in figure <<interpret-espressopp-script>> describes how an
{espressopp} script is interpreted into a native query.

[[interpret-espressopp-script]]
.Scenario Interpret {espressopp} Script
[plantuml, format="png", id="interpret-espressopp-script"]
----
actor Client
create EspressoppInterpreter
Client --> EspressoppInterpreter : new
create Parser
EspressoppInterpreter --> Parser : new
create Reader
Client --> Reader : new
create Writer
Client --> Writer : new
create SqlCodeGenerator
Client --> SqlCodeGenerator : new
Client -> EspressoppInterpreter : Accept(codeGenerator, reader, writer)
activate EspressoppInterpreter
EspressoppInterpreter -> SqlCodeGenerator : Visit(interpreter, reader, writer)
activate SqlCodeGenerator
SqlCodeGenerator -> EspressoppInterpreter : Parse(reader)
EspressoppInterpreter -> Parser : Parse(reader)
activate Parser
Parser -> Reader : Read()
activate Reader
return script
return grammar
EspressoppInterpreter --> SqlCodeGenerator : grammar
deactivate EspressoppInterpreter
SqlCodeGenerator -> SqlCodeGenerator : generateSql
activate SqlCodeGenerator
return sql
SqlCodeGenerator -> Writer : Write(sql)
activate Writer
deactivate SqlCodeGenerator
deactivate Writer
Client -> Writer : String()
activate Writer
return sql
----
{empty} +

The `Interpreter` is initialized by the _Client_ and provides functionality for parsing {espressopp}
scripts to be converted into native queries by the `CodeGenerator`. The `CodeGenerator` is also
initialized by the _Client_ and gets _accepted_ together with the `Reader` and `Writer` by the
`Interpreter` -- this construct allows the `CodeGenerator` to access the `Parser` instantiated by the
`Interpreter` and get back the {espressopp} _grammar_.

The `Reader` is where the {espressopp} script is read from by the `Parser`, whereas the `Writer`
is where the `CodeGenerator` writes the resulting native query.

By default field names in the input {espressopp} expression remain unchanged in the output native
query. Should not the fields in the {espressopp} expression match the name of the fields in the
underlying databse, a mapping needs to be provided by calling `MapFieldNames`.

[[process-view]]
== Process View

The process view describes the concurrent aspects of the system, namely the tasks (or processes)
that make the system run and the interactions between them. {espressopp} is a module to be included
into other applications. However, {espressopp} ships with a command-line utility that takes an
{espressopp} espression as an input and returns the resulting native query.

The diagram depicted in figure <<process-composition>> describes the process composition of the
{espressopp} command-line utility and the mapping of resources on it.

[[process-composition]]
.Process Composition
[plantuml, format="png", id="process-composition"]
----
class espressopp <<process>> {
  interpreter: EspressoppInterpreter
  codeGenerator: SqlCodeGenerator
  reader: io.Reader
  writer: io.Writer
}
----
{empty} +

The {espressopp} command-line utility uses the `Interpreter` and `CodeGenerator` exactly the same way
client applications do. It is just meant to help developers debug filters written in the {espressopp}
language.

---

*Copyright &#169; 2020 Skeeter Health*
