actor Client
create Espressopp
Client --> Espressopp : new
create Parser
Espressopp --> Parser : new
create Reader
Client --> Reader : new
create Writer
Client --> Writer : new
create SqlCodeGenerator 
Client --> SqlCodeGenerator : new
Client -> Espressopp : Accept(codeGenerator, reader, writer)
activate Espressopp 
Espressopp -> SqlCodeGenerator : Visit(interpreter, reader, writer)
activate SqlCodeGenerator 
SqlCodeGenerator -> Espressopp : Parse(reader)
Espressopp -> Parser : Parse(reader)
activate Parser
Parser -> Reader : Read()
activate Reader
return script
return grammar
Espressopp --> SqlCodeGenerator : grammar
deactivate Espressopp 
SqlCodeGenerator -> SqlCodeGenerator : generateSql
activate SqlCodeGenerator 
return sql
SqlCodeGenerator -> Writer : Write(sql)
activate Writer
deactivate SqlCodeGenerator 
deactivate Writer
Client -> Writer : String()
activate Writer
return sql
